#!/usr/bin/env python3

import datetime
import json
import os
import sys
import uuid

mylogin = os.getlogin()
timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

output = {}
ostrings = {}
languages = []
localisationfile = { 'Version': 2, 'UUID': str(uuid.uuid4()), 'Languages': languages, 'Strings': ostrings}
output['LocalisationFile'] = localisationfile

istrings = {}
for f in sys.argv[1:]:
    input = json.load(open(f))
    lang = input['Language']
    istrings[lang] = input['Strings']

for lang in istrings:
    languages.append(lang)
    for string in istrings[lang]:
        if not string in ostrings:
            ostrings[string] = { 'UUID': str(uuid.uuid4()),
                                 'LastModifiedBy': mylogin,
                                 'LastModifiedDate': timestamp,
                                 'LocalizationStatus': 'TranslationNeeded',
                                 'Languages': {}
                                }
        ostrings[string]['Languages'][lang] = { 'Text': istrings[lang][string] }
        if lang == 'en-US':
            ostrings[string]['Languages'][lang]['LocalizationStatus'] = 'TranslationNeeded'

json.dump(output, sys.stdout, indent=2)
sys.stdout.write('\n')
